import pygame

NUM_OF_FLOORS = 8
NUM_OF_LIFTS = 2

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700


TEXT_MARGIN = 5

MARGIN = 10

FLOOR_HEIGHT = 90
FLOOR_WIDTH = 180
HORIZ_CENTER = MARGIN + FLOOR_WIDTH // 2

LIFT_SIZE = FLOOR_HEIGHT, FLOOR_HEIGHT

SPACER_HEIGHT = 7


WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREY = (128, 128, 128)
GREEN = (0, 255, 0)
BLUE = (0, 0, 200)

BUTTON_RADIUS = 13
VERT_NUM_MOVE = -7

TIMER_WIDTH = FLOOR_WIDTH // 2 - BUTTON_RADIUS - MARGIN * 2
TIMER_HEIGHT = BUTTON_RADIUS * 2

LIFT_PIC = pygame.transform.scale(pygame.image.load('resources/elv.png'), LIFT_SIZE)
FLOOR_PIC = pygame.transform.scale(pygame.image.load('resources/floor_pic.jpg'), (FLOOR_WIDTH, FLOOR_HEIGHT))
DING_SOUND = 'resources/ding.mp3'

SECONDS_PER_FLOOR = .5
MILLISECONDS_PER_FLOOR = SECONDS_PER_FLOOR * 1000
PIXELS_PER_SECOND = int(FLOOR_HEIGHT / SECONDS_PER_FLOOR)
PIX_PER_MILLISECOND = PIXELS_PER_SECOND / 1000

LIFT_STOP_TIME = 2000

# FPS = 30
# CONSTANT_INCREMENT = FLOOR_HEIGHT * 2 // FPS