import pygame
# from Lift import *
# from Lift import Lift



NUM_OF_FLOORS = 8
NUM_OF_LIFTS = 2

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700

MARGIN = 10

FLOOR_HEIGHT = 90
FLOOR_WIDTH = 180
HORIZ_CENTER = MARGIN + FLOOR_WIDTH // 2

LIFT_SIZE = FLOOR_HEIGHT, FLOOR_HEIGHT
# LIFT_X = MARGIN + FLOOR_WIDTH + MARGIN

SPACER_HEIGHT = 7


WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
LIGHT_RED = (140, 0, 0)
GREY = (128, 128, 128)
GREEN = (0, 255, 0)
BLUE = (0, 0, 200)
OPAQUE_GREY = (128, 128, 128, 0.5)

BUTTON_RADIUS = 13
# HORIZ_NUM_MOVE = -4
VERT_NUM_MOVE = -7

BUTTON_LEFT_EDGE = MARGIN + FLOOR_WIDTH // 2 - BUTTON_RADIUS
BUTTON_RIGHT_EDGE = MARGIN + FLOOR_WIDTH // 2 + BUTTON_RADIUS

LIFT_PIC = pygame.transform.scale(pygame.image.load('resources/elv.png'), LIFT_SIZE)
FLOOR_PIC = pygame.transform.scale(pygame.image.load('resources/floor_pic.jpg'), (FLOOR_WIDTH, FLOOR_HEIGHT))
DING_SOUND = 'resources/ding.mp3'

SECONDS_PER_FLOOR = .5
PIXELS_PER_SECOND = int(FLOOR_HEIGHT / SECONDS_PER_FLOOR)
PIX_PER_MILISECOND = PIXELS_PER_SECOND / 1000

LIFT_STOP_TIME = 2000

FPS = 30
CONSTANT_INCREMENT = FLOOR_HEIGHT * 2 // FPS